### ISSUE TITLE
React 18 Support

### ISSUE THREAD

**Issue by michigg** [ljcl/storybook-addon-cssprops#27]
I installed storybook in a vue project today. After that I wanted to install the cssprops addon but I get the following error.

![grafik](https://user-images.githubusercontent.com/28068636/173333138-c3e4231f-52e5-49bb-9acd-68cd5fa42047.png)

It seems that only the react versions 16 and 17 are supported but storybook seem to use the version 18.
After I force installed it, it seem to work without any errors.

Can the addon be upgraded to support the react version 18 too?

**Comment by ljcl** [comment]
Have added this in #28, should be available in the latest release
