### ISSUE TITLE
Need to refresh to reset

### ISSUE THREAD

**Issue by mgohin** [ljcl/storybook-addon-cssprops#3]
Hi,

thanks a lot for this addon, very useful for us !

When I click the reset button, nothing live happens, I need to refresh the page (F5) to apply the reset.

Version `"@ljcl/storybook-addon-cssprops": "^0.1.0"`

**Comment by ljcl** [comment]
Thanks for the report, I'll try to take a look at it soon. But you're welcome to take a shot at it if you'd like to.

**Comment by mgohin** [comment]
I tried to dig in, but I've never done React :D

**Comment by ljcl** [comment]
Fixed in version 2.0.0 (#9)

**Comment by mgohin** [comment]
Tested it in 2.3.2 and it works, thanks
