### ISSUE TITLE
does not display css custom properties without a value defined

### ISSUE THREAD

**Issue by MatteoWebDeveloper** [ljcl/storybook-addon-cssprops#35]
- On Storybook doc, storybook-addon-cssprops does not display css vars that do no have a value properties
```js
parameters: {
    cssprops: {
      'alert-width': { control: 'text' },
    },
  },
```
- On Canvas panel using the same configuration in the previous case, when you click on set string nothing happen
<img width="1302" alt="Screenshot 2023-01-30 at 14 26 50" src="https://user-images.githubusercontent.com/4461152/215504513-7acea312-2010-48cb-a654-02475e01a225.png">

Happy to contribute to this project and cover the above use cases

**Comment by ljcl** [comment]
Welcome a pr if you'd like to work on this 😃

**Comment by MatteoWebDeveloper** [comment]
sorry @ljcl, I was thinking to contribute but I end up using storybook controls in the end.
