### ISSUE TITLE
Storybook 8 compatibility

### ISSUE THREAD

**Issue by kwickramasekara** [ljcl/storybook-addon-cssprops#45]
It looks like the plugin may need some updates to work with the recently updated Storybook 8. I am seeing the following errors in v8:

<img width="868" alt="image" src="https://github.com/ljcl/storybook-addon-cssprops/assets/6528584/fb9e6b9f-24cf-49f4-8b1b-986475667f1e">

**Comment by gethari** [comment]
@ljcl is there a plan to upgrade ? or I can possibly try a PR if that's ok ?

**Comment by ljcl** [comment]
Keen for you to give it a shot!

**Comment by kwickramasekara** [comment]
@ljcl just submitted a PR (#46) for Storybook 8 support. Please review at your earliest 🙏
